language: java
sudo: false

before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
   - echo $JAVA_HOME
   
matrix:
  include:
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11

os:
  - linux

notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
