language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk7
#  - openjdk8
  - openjdk7
  - openjdk6
os:
  - linux
  - osx
notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"
