language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk7
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: linux
      jdk: openjdk10
    - os: linux
      jdk: openjdk11
    - os: osx
      # This uses Oracle JDK 8
      osx_image: xcode9.3
    - os: osx
      jdk: openjdk11
      osx_image: xcode10.1

dist: xenial

notifications:
  irc:
    channels:
      - "irc.freenode.org#jnr"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{branch}:%{commit} by %{author}): %{message} (%{build_url})"

